package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class EditProductsController {
	@FXML
	private ListView productListView;
	@FXML
	private Button addButton;
	@FXML
	private Button editButton;
	@FXML
	private Button removeButton;
	@FXML
	private Button closeButton;

	// Event Listener on Button[#addButton].onAction
	@FXML
	public void addButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editButton].onAction
	@FXML
	public void editButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#removeButton].onAction
	@FXML
	public void removeButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#closeButton].onAction
	@FXML
	public void closeButtonClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
